### ISSUE TITLE
ERROR: LoadError: DimensionMismatch("arrays could not be broadcast to a common size; got a dimension with lengths 652 and 139")

### ISSUE THREAD

**Issue by jarroyoe** [SciML/SciMLBase.jl#102]
I am trying to run an UDE of a Rosenzweig-MacArthur model with noisy data. I get the following Warning and Error when I try to run it.
`┌ Warning: Interrupted. Larger maxiters is needed.
└ @ SciMLBase ~/.julia/packages/SciMLBase/UIp7W/src/integrator_interface.jl:331
ERROR: LoadError: DimensionMismatch("arrays could not be broadcast to a common size; got a dimension with lengths 652 and 139")`

Here's the data for further checking
[RM_data.csv](https://github.com/SciML/SciMLBase.jl/files/7117255/RM_data.csv)

And the relevant code
```
X = CSV.read("Data/RM_data.csv",DataFrame)
println(first(X))
ts = X.timestamp
Xs = X.value1
Ys = X.value2
Zs = X.value3

##Generate subsamples of data
TS_length = length(Xs)
println(TS_length)
N_samples = 5
subsampleLength = floor(Int64,TS_length/N_samples)

#Subsample the data
#We assume we have only 5 measurements, evenly distributed
TS = zeros(N_samples,subsampleLength)
XS = zeros(N_samples,subsampleLength)
YS = zeros(N_samples,subsampleLength)
ZS = zeros(N_samples,subsampleLength)

for i in 1:N_samples
    println(i)
    XS[i, :] = Xs[((i-1)*subsampleLength+1):(i*subsampleLength)]
    YS[i, :] = Ys[((i-1)*subsampleLength+1):(i*subsampleLength)]
    ZS[i, :] = Zs[((i-1)*subsampleLength+1):(i*subsampleLength)]
    TS[i, :] = ts[((i-1)*subsampleLength+1):(i*subsampleLength)]
end

#Define nonlinear network
# Gaussian RBF as activation
rbf(x) = exp.(-(x.^2))

# Define the network 3->5->5->3
U = FastChain(
    FastDense(3,5,rbf), FastDense(5,5, rbf), FastDense(5,3)
)

#Define the initial parameters
p = vcat(rand(Float32,8), initial_params(U))
#p = rand(Float32,8)

#Define hybrid model
function ude_dynamics!(du,u, p, t, p_true)
    r = p[1]
    K = p[2]
    a2 = p[3]
    c2 = p[4]
    d2 = p[5]
    a3 = p[6]
    d3 = p[7]
    c3 = p[8]

    û = U(u, p[9:end]) # Network prediction
    #Define the known dynamics
    du[1] = r*u[1]*(1-u[1]/K) - a2*u[1]*u[2]/(1+u[1]) + û[1]
    du[2] = c2*a2*u[1]*u[2]/(1+u[1]) - d2*u[2] - a3*u[2]*u[3]/(1+u[2]) + û[2]
    du[3] = c3*a3*u[2]*u[3]/(1+u[2]) - d3*u[3] + û[3]
end

# Closure with the known parameter
nn_dynamics!(du,u,p,t) = ude_dynamics!(du,u,p,t,nothing)
# Define the problem
prob_nn = ODEProblem(nn_dynamics!,[XS[1,1],YS[1,1],ZS[1,1]], (ts[1],ts[end]), p)

## Function to train the network
# Define a predictor
function predict(θ, X = X[:,1], T = ts)
    Array(solve(prob_nn, Vern7(), u0 = X, p=θ,
                tspan = (T[1], T[end]), saveat = T,
                abstol=1e-6, reltol=1e-6,
                sensealg = ForwardDiffSensitivity()
                ))
end

# Multiple shooting like loss
function loss(θ)
    # Start with a regularization on the network
    l = convert(eltype(θ), 1e-3)*sum(abs2, θ) ./ length(θ)
    for i in 1:size(XS,1)
        XX= predict(θ, [XS[i,1], YS[i,1], ZS[i,1]], TS[i, :])
        # Full prediction in x
        l += sum(abs2, XS[i,:] .- XX[1,:])
        l += sum(abs2, YS[i, :] .- XX[2, :])
        l += sum(abs2, ZS[i, :] .- XX[3, :])
    end
    return l
end

# Container to track the losses
losses = Float32[]

# Callback to show the loss during training
callback(θ,l) = begin
    push!(losses, l)
    if length(losses)%50==0
        println("Current loss after $(length(losses)) iterations: $(losses[end])")
    end
    false
end

## Training

# First train with ADAM for better convergence -> move the parameters into a
# favourable starting positing for BFGS
res1  = DiffEqFlux.sciml_train(loss, p, ADAM(0.1f0), cb=callback, maxiters = 10000)
# Train with BFGS
res2 = DiffEqFlux.sciml_train(loss, res1.minimizer, BFGS(initial_stepnorm=0.01f0), cb=callback, maxiters = 10000, g_tol = 1e-10)
println("Final training loss after $(length(losses)) iterations: $(losses[end])")

# Plot the losses
pl_losses = plot(1:10000, losses[1:10000], yaxis = :log10, xaxis = :log10, xlabel = "Iterations", ylabel = "Loss", label = "ADAM", color = :blue)
plot!(10001:length(losses), losses[10001:end], yaxis = :log10, xaxis = :log10, xlabel = "Iterations", ylabel = "Loss", label = "BFGS", color = :red)
#savefig(pl_losses, joinpath(pwd(), "plots", "$(svname)_losses.pdf"))

# Rename the best candidate
p_trained = res2.minimizer
```

I don't get any print of the callback, which makes me assume that it fails on the first iteration (especially since increasing the number of iterations doesn't change the result). I tried running the equivalent NODE (commenting any reference to û) and got prints of the callback and the process finishes, which tells me the issue is being caused by the û term.

**Comment by ChrisRackauckas** [comment]
Is it stiff? You're using a non-stiff solver and get a maxiters warning. That's one of the FAQ: https://diffeq.sciml.ai/stable/basics/faq/#A-larger-maxiters-seems-to-be-needed,-but-it's-already-high?

**Comment by jarroyoe** [comment]
I keep getting similar warnings. Now instead of maxiters warning, I'm getting stability warnings.

With Rodas5():  `Instability detected. Aborting`
With Rosenbrock23(): maxiters as well
With TRBDF2(): `dt <= dtmin. Aborting. There is either an error in your model specification or the true solution is unstable.`
With KenCarp4(): `dt <= dtmin. Aborting. There is either an error in your model specification or the true solution is unstable.`
With QNDF(): `dt <= dtmin. Aborting. There is either an error in your model specification or the true solution is unstable.`

I know the original DE is not unstable because the corresponding NODE problem worked correctly, so the instabilities are being produced by the NN.

Should I try with different NN architectures?

**Comment by ChrisRackauckas** [comment]
Is the forward solve unstable of the NODE for the starting parameters even without optimization? This looks like it could be a definitional problem of the ODE. Many times this could happen if the NODE has positive eigenvalues and you have a time span that is too long.

**Comment by jarroyoe** [comment]
To double check, I ran the [NODE tutorial](https://diffeqflux.sciml.ai/dev/examples/neural_ode_sciml/) with my data and my model. I was getting a similar error as the one in the title until I realized my data does not have a fixed time step.

Resimulated my data with a fixed time step and now NODE works but UDE gives me the following warning, which leads to an error in the callback:

`ERROR: LoadError: MethodError: no method matching callback(::Vector{Float32WARNING: both Flux and Iterators export "flatten"; uses of it in module DiffEqFlux must be qualified
WARNING: both Flux and Distributions export "params"; uses of it in module DiffEqFlux must be qualified
}, ::Float64, ::Matrix{Float64})`

Where does it specify the type of 'flatten' I need (I guess it's the one in Flux)?

PS: Probably something not important for now, but is there a way to use these algorithms without specifying the length of the solution matrix in the solve function (letting the adaptive algorithms do their own work)?

**Comment by ChrisRackauckas** [comment]
Did you make saveat match your times? 

>but is there a way to use these algorithms without specifying the length of the solution matrix in the solve function (letting the adaptive algorithms do their own work)?

Yes, saveat will let the adaptive algorithm do it's own thing and only effect the saving. I don't see how you can compare to data without specifying the save times.

**Comment by jarroyoe** [comment]
Yes, the saveat matches the time of my dataset. I double checked and the output of the predict function matches the size of my training time series.

**Comment by ChrisRackauckas** [comment]
Just running this shows the problem:

```julia
using CSV, DiffEqFlux, DataFrames, OrdinaryDiffEq
X = CSV.read("RM_data.csv",DataFrame)
println(first(X))
ts = X.timestamp
Xs = X.value1
Ys = X.value2
Zs = X.value3

##Generate subsamples of data
TS_length = length(Xs)
println(TS_length)
N_samples = 5
subsampleLength = floor(Int64,TS_length/N_samples)

#Subsample the data
#We assume we have only 5 measurements, evenly distributed
TS = zeros(N_samples,subsampleLength)
XS = zeros(N_samples,subsampleLength)
YS = zeros(N_samples,subsampleLength)
ZS = zeros(N_samples,subsampleLength)

for i in 1:N_samples
    println(i)
    XS[i, :] = Xs[((i-1)*subsampleLength+1):(i*subsampleLength)]
    YS[i, :] = Ys[((i-1)*subsampleLength+1):(i*subsampleLength)]
    ZS[i, :] = Zs[((i-1)*subsampleLength+1):(i*subsampleLength)]
    TS[i, :] = ts[((i-1)*subsampleLength+1):(i*subsampleLength)]
end

#Define nonlinear network
# Gaussian RBF as activation
rbf(x) = exp.(-(x.^2))

# Define the network 3->5->5->3
U = FastChain(
    FastDense(3,5,rbf), FastDense(5,5, rbf), FastDense(5,3)
)

#Define the initial parameters
p = vcat(rand(Float32,8), initial_params(U))
#p = rand(Float32,8)

#Define hybrid model
function ude_dynamics!(du,u, p, t, p_true)
    r = p[1]
    K = p[2]
    a2 = p[3]
    c2 = p[4]
    d2 = p[5]
    a3 = p[6]
    d3 = p[7]
    c3 = p[8]

    û = U(u, p[9:end]) # Network prediction
    #Define the known dynamics
    du[1] = r*u[1]*(1-u[1]/K) - a2*u[1]*u[2]/(1+u[1]) + û[1]
    du[2] = c2*a2*u[1]*u[2]/(1+u[1]) - d2*u[2] - a3*u[2]*u[3]/(1+u[2]) + û[2]
    du[3] = c3*a3*u[2]*u[3]/(1+u[2]) - d3*u[3] + û[3]
end

# Closure with the known parameter
nn_dynamics!(du,u,p,t) = ude_dynamics!(du,u,p,t,nothing)
# Define the problem
prob_nn = ODEProblem(nn_dynamics!,[XS[1,1],YS[1,1],ZS[1,1]], (ts[1],ts[end]), p)

## Function to train the network
# Define a predictor
function predict(θ, X = X[:,1], T = ts)
    Array(solve(prob_nn, Vern7(), u0 = X, p=θ,
                tspan = (T[1], T[end]), saveat = T,
                abstol=1e-6, reltol=1e-6,
                sensealg = ForwardDiffSensitivity()
                ))
end

# Multiple shooting like loss
function loss(θ)
    # Start with a regularization on the network
    l = convert(eltype(θ), 1e-3)*sum(abs2, θ) ./ length(θ)
    for i in 1:size(XS,1)
        XX= predict(θ, [XS[i,1], YS[i,1], ZS[i,1]], TS[i, :])
        # Full prediction in x
        l += sum(abs2, XS[i,:] .- XX[1,:])
        l += sum(abs2, YS[i, :] .- XX[2, :])
        l += sum(abs2, ZS[i, :] .- XX[3, :])
    end
    return l
end

# Container to track the losses
losses = Float32[]

# Callback to show the loss during training
callback(θ,l) = begin
    push!(losses, l)
    if length(losses)%50==0
        println("Current loss after $(length(losses)) iterations: $(losses[end])")
    end
    false
end

loss(p)  # Warning: Interrupted. Larger maxiters is needed.
```

It can't work if the starting parameters already diverge! So this has nothing to do with the training process. What you need to do is what I explained above: change to a method for stiff equations (just for stability), and then use a more stable fitting procedure like https://diffeqflux.sciml.ai/dev/examples/local_minima/ or https://diffeqflux.sciml.ai/dev/examples/multiple_shooting/ . If you use an unstable fitting procedure on an unstable problem, you get something unstable. When stablizing small time spans before expanding this seems to turn out fine.

**Comment by jarroyoe** [comment]
Thank you, I've managed to make it work almost consistently using the Rosenbrock23 method with a relative tolerance of 0.1 and a multi shoot approach. However, sometimes it converges to a suboptimal minimum (RMSE around 180) and some other times it finds a better minimum, but the problem becomes too stiff around a RMSE of 9 and halts.

I've tried several stiff methods and relative tolerances to no avail. What other parameters might be possible to change? Is there a way to store the intermediate parameters to have access to them even if the problem halts? (Probably a bad programming decision, but if it's a possibility might be worth exploring).

**Comment by ChrisRackauckas** [comment]
>  with a relative tolerance of 0.1

That is extremely high. Most would recommend you never have the relative tolerance that high.

>I've tried several stiff methods and relative tolerances to no avail. What other parameters might be possible to change? Is there a way to store the intermediate parameters to have access to them even if the problem halts? (Probably a bad programming decision, but if it's a possibility might be worth exploring).

GalacticOptim will always store them by default. But it would be good to just stabilize the training first. Watch your default definition.

**Comment by jarroyoe** [comment]
Thanks, I had to decrease the relative tolerance and absolute tolerances to 1e-16 for the solution to be consistently stable, but it worked.

**Comment by ChrisRackauckas** [comment]
👍 multiple shooting could help as well.
