### ISSUE TITLE
Different AD backends for objective and constraints

### ISSUE THREAD

**Issue by baggepinnen** [SciML/SciMLBase.jl#117]
While the objective function is typically scalar, constraint functions may have a very large output arity. There may thus be situations where it's beneficial to differentiate the objective in reverse, but calculate the constraint jacobian in forward mode.

**Comment by ChrisRackauckas** [comment]
That's a question for GalacticOptim, and I think it might already have an issue from @jlperla

**Comment by jlperla** [comment]
There wasn't, but there should be.  Added https://github.com/SciML/GalacticOptim.jl/issues/191
