### ISSUE TITLE
Add median to `EnsembleSummary`

### ISSUE THREAD

**Issue by nathanaelbosch** [SciML/SciMLBase.jl#132]
Right now, EnsembleSummary contains the mean, variance, and quantiles. The corresponding plot recipe plots (by default) the mean, and the quantiles as ribbons. This can lead to unexpected plots for cases with strong outliers, where the line lies outside of the ribbon.

**Proposal:** Add the median to the ensemble summary. Then plot either the median (line) and the quantiles (ribbon) for `ci_type=:quantile` or the mean and variance as currently done when `ci_type=:SEM`.

**Comment by ChrisRackauckas** [comment]
Sounds good.

**Comment by homocomputeris** [comment]
> median (line) and the quantiles (ribbon)

I think it's worth explicitly mentioning in [the docs](https://docs.sciml.ai/DiffEqDocs/stable/features/ensemble/#Plot-Recipe-2) that the line is the median.
