### ISSUE TITLE
First batch not counted in simulation time when solving EnsembleProblems.

### ISSUE THREAD

**Issue by brainsMAKER** [SciML/SciMLBase.jl#190]
Hi,

I found a minor issue when solving `EnsembleProblem`s.

Due to the way the `@elapsed` are placed in this function :
```julia
 __solve(prob::AbstractEnsembleProblem,  alg::Union{DEAlgorithm,Nothing}, ensemblealg::BasicEnsembleAlgorithm; kwargs...)
```
if there are mutiple bathes or `prob.reduction !== DEFAULT_REDUCTION`  then the first batch does not count in the simulation time (see below).
https://github.com/SciML/SciMLBase.jl/blob/9788d32ebcae15199fa690c44cdde1821ae2abf9/src/ensemble/basic_ensemble_solve.jl#L55-L82

This is especially bad when reduction is needed but there is only one batch (e.g. when trying to avoid a race condition with `EnsembleThreads()`  ) or if the number of batches is low.

I believe an easy fix would be moving the second `@elapsed` before the first batch using a `begin ... end` block :

https://github.com/brainsMAKER/SciMLBase_.jl/blob/b76a9970becb54c5c94e83ea9ae105913ca00003/src/ensemble/basic_ensemble_solve.jl#L62-L81

**Comment by ChrisRackauckas** [comment]
Ahh yes, thanks for pointing this out. Your suggested fix does seem to be correct. Would you mind making a PR?

**Comment by brainsMAKER** [comment]
> Ahh yes, thanks for pointing this out. Your suggested fix does seem to be correct. Would you mind making a PR?

I made a PR with the proposed fix and corresponding test :
https://github.com/SciML/SciMLBase.jl/pull/192

First time here, so I hope I did it alright !

**Comment by ChrisRackauckas** [comment]
That was great thanks
