### ISSUE TITLE
kwargs field makes `IntegralProblem` type unstable

### ISSUE THREAD

**Issue by sharanry** [SciML/SciMLBase.jl#191]
```julia
function copy_(prob)
    prob_ = IntegralProblem(prob.f, prob.lb, prob.ub, prob.p , nout = prob.nout , batch = prob.batch , prob.kwargs...) 
end
@code_warntype copy_(prob)
```

# Related
- https://github.com/SciML/Integrals.jl/issues/65

CC: @ChrisRackauckas @YingboMa

**Comment by sharanry** [comment]
@ChrisRackauckas is it okay to remove that field? That would enable making `transformation_if_inf` in https://github.com/SciML/Integrals.jl/issues/65 type stable.

**Comment by ChrisRackauckas** [comment]
Can we make it type stable by making it a namedtuple?

It's supposed to be passed on as is normal for the other probs. It's a bug that it isn't.
