### ISSUE TITLE
`set_u!` with symbols

### ISSUE THREAD

**Issue by AayushSabharwal** [SciML/SciMLBase.jl#206]
Currently modifying the state of an integrator requires passing a `Vector` to `set_u!`, which is nontrivial when dealing with larger systems. Is there a way to do this symbolically, that I can't find? E.g. `set_u!(integrator, x, 1.23)`? Would this be feasible to implement?

**Comment by ChrisRackauckas** [comment]
That would be feasible.

**Comment by AayushSabharwal** [comment]
This will require a PR both here (for the `set_u!` method) and in ODE.jl (for implementing the method)
