### ISSUE TITLE
idxs vs. vars for accessing solution values 

### ISSUE THREAD

**Issue by isaacsas** [SciML/SciMLBase.jl#207]
It would be nice if the same keyword could be used in plotting and in evaluating solutions for specific components, i.e. `sol(t; vars=[...])` and `plot(sol; vars=[...])` or vice-versa with `idxs`.

**Comment by ChrisRackauckas** [comment]
vars should probably be deprecated because everything other than plotting uses `idxs`.

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/SciMLBase.jl/pull/211
