### ISSUE TITLE
Many functions on `AbstractODESolution` return actual `ODESolution`s

### ISSUE THREAD

**Issue by nathanaelbosch** [SciML/SciMLBase.jl#212]
https://github.com/SciML/SciMLBase.jl/blob/master/src/solutions/ode_solutions.jl defines a range of functions, which operate on `AbstractODESolution`s, and yet return `ODESolution`s. This is particularly confusing for cases such as `solution_new_retcode` or `solution_new_tslocation`. For example, if I implement my own `MySolution <: AbstractODESolution` then it silently gets transformed into a `ODESolution`. I would argue that defining these functions on `ODESolution` would therefore be more appropriate, so that an error is raised.

The relevant functions here are:
- build_solution
- solution_new_retcode
- solution_new_tslocation
- solution_slice
- sensitivity_solution

**Comment by ChrisRackauckas** [comment]
Good point. These should probably be more restrictive.

**Comment by nathanaelbosch** [comment]
Closed via #213.
