### ISSUE TITLE
Integrator symbolic indexing should support parameters

### ISSUE THREAD

**Issue by wsphillips** [SciML/SciMLBase.jl#231]
`getindex(A::DEIntegrator, sym)` can flexibly return states, independent variable, and observed variables, but not system parameters. 

I would like subtypes of `AbstractDiffEqFunction{iip}` (those used by MTK) to have a kwarg and field equivalent to `syms`, called `paramsyms`. That would allow modifying the `getindex` method to support all possible system symbols. The changes here would need to be propagated to the contructor calls in `ModelingToolkit.jl`

https://github.com/SciML/SciMLBase.jl/blob/f348d7c377aaa8006069971f5dc3bba6b89fabce/src/integrator_interface.jl#L415-L437

**Comment by ChrisRackauckas** [comment]
I think this is reasonable. @AayushSabharwal if you have time this would be good to handle.

**Comment by AayushSabharwal** [comment]
Sure, I'll try and get this done
