### ISSUE TITLE
Accessing parameters from the solution

### ISSUE THREAD

**Issue by ValentinKaisermayer** [SciML/SciMLBase.jl#259]
I'm not sure if this is supposed to work:

```julia
using ModelingToolkit
using DifferentialEquations

@variables t x(t) 
@parameters tau
D = Differential(t)

@named fol = ODESystem([D(x)  ~ (1 - x) / tau])
prob = ODEProblem(fol, [x => 0.0], (0.0, 10.0), [tau => 3.0])
sol = solve(prob)
sol[tau]

ERROR: type ODECompositeSolution has no field p
```
Issue is around here:
https://github.com/SciML/SciMLBase.jl/blob/f1a9cded96420c052cf43a096288df97988e2beb/src/solutions/solution_interface.jl#L79

should it be `A.prob.p`?

**Comment by ChrisRackauckas** [comment]
Yes it should be. Can you also add this test? Reduce it to just OrdinaryDiffEq but it would be good to have the `AutoTsit5(Rosenbrock23())` solve in there.

**Comment by ValentinKaisermayer** [comment]
For now this is fine but since the parameters can be changed via a callback the solution should store the parameters as a vector as well and not just return the value from the problem.
