### ISSUE TITLE
NonlinearProblem docs claim to accept ODE-problem

### ISSUE THREAD

**Issue by jaakkor2** [SciML/SciMLBase.jl#265]
```
help?> NonlinearProblem
```
last entry I see is
```
  NonlinearProblem(prob)


  Define a steady state problem from a standard ODE problem.
```
This originates from

https://github.com/SciML/SciMLBase.jl/blob/v1.59.4/src/problems/basic_problems.jl#L174-L180

**Comment by ChrisRackauckas** [comment]
oh thanks, that dispatch should get fixed up.

**Comment by ChrisRackauckas** [comment]
Fixed in https://github.com/SciML/SciMLBase.jl/pull/283
