### ISSUE TITLE
`isinplace` fails for RuntimeGeneratedFunction

### ISSUE THREAD

**Issue by baggepinnen** [SciML/SciMLBase.jl#268]
This line
```julia
methods(f).ms[1].sig.parameters)
```
https://github.com/SciML/SciMLBase.jl/blob/5ebd493ed27facbaf6a33d20a8c59e6b4aba7057/src/utils.jl#L192
fails if `f` is a RuntimeGeneratedFunction
```
ERROR: type UnionAll has no field parameters
```
I'll work on a MWE

**Comment by ChrisRackauckas** [comment]
But MTK always generates AbstractSciMLFunctions with an IIP designation, so this isn't hit anywhere?

**Comment by baggepinnen** [comment]
The user could generate a function themselves and stick in an `ODEFunction`? At least that's how I ran into the problem. I worked around it by manually specifying the in-place type parameter for now

**Comment by ChrisRackauckas** [comment]
Yeah if you specify it then you should be fine. 

I guess you could use the argnames type tag to get the length https://github.com/SciML/RuntimeGeneratedFunctions.jl/blob/master/src/RuntimeGeneratedFunctions.jl#L51
