### ISSUE TITLE
Indexing of integrator/solution with collection doesn't return same type as passed in

### ISSUE THREAD

**Issue by AayushSabharwal** [SciML/SciMLBase.jl#273]
https://github.com/SciML/SciMLBase.jl/blob/1ecf19e8404cb3e043520c0515483768c6bed0f7/src/integrator_interface.jl#L426

Why is there a `collect` here? If `sym isa AbstractArray`, collecting it just forces it to be a `Vector` which means a `Vector` is always returned. It's impossible to pass in an `SVector` and get back an `SVector`

**Comment by ChrisRackauckas** [comment]
Indeed that would be nice to generalize. I think it could be done through broadcast on getindex?

**Comment by AayushSabharwal** [comment]
It should be. I'll add it to #272 and add a test for it
