### ISSUE TITLE
Handling return codes of optimization problem

### ISSUE THREAD

**Issue by ValentinKaisermayer** [SciML/SciMLBase.jl#312]
Currently the return codes are `SciMLBase.ReturnCode`: 
https://github.com/SciML/SciMLBase.jl/blob/master/src/solutions/optimization_solutions.jl#L26

However, Optimization.jl yields a `Symbol`. For MOI solvers the MOI return code is hence always converted to `ReturnCode.Failure = 9`

**Comment by ValentinKaisermayer** [comment]
MOI TerminationStatusCodes: https://github.com/jump-dev/MathOptInterface.jl/blob/1b7bec4885a8304ca84d6789843aae70b468f16f/src/attributes.jl#L1938

**Comment by ChrisRackauckas** [comment]
We should convert as we see fit, and add some more if we need to.

**Comment by ChrisRackauckas** [comment]
For starters, just convert to Success and Failure. We can get more granular over time.
