### ISSUE TITLE
Documentation issue in OptimizationProblem

### ISSUE THREAD

**Issue by DanielVandH** [SciML/SciMLBase.jl#331]
https://github.com/SciML/SciMLBase.jl/blob/b584ec05f84da9b8ebfa7b3fca1f6348f7f1a2fe/src/problems/basic_problems.jl#L421-L423

Is this part `jac = true, eval_module = @__MODULE__)ed` supposed to render into something in the docs? When I view it in the actual documentation (https://docs.sciml.ai/Optimization/stable/API/optimization_problem/, or in `?OptimizationProblem`) I see exactly `If f is a standard Julia function, it is automatically , jac = true, eval_module = @MODULE)ed into an OptimizationFunction with NoAD(), i.e., no automatic generation of the derivative functions.`.

I assume the correct statement is something like:
> If `f` is a standard Julia function, it is automatically transformed into an `OptimizationFunction` with `NoAD()`, meaning the derivative functions are not automatically generated.

**Comment by ChrisRackauckas** [comment]
You are correct. I have no idea how it got like that maybe some first draft blues of grabbing some stuff from ModelingToolkit
