### ISSUE TITLE
OptimizationFunction requiring function to have hyperparameters argument?

### ISSUE THREAD

**Issue by tom-plaa** [SciML/SciMLBase.jl#336]
OptimizationFunction now needs to be provided with a function f(u,p); I believe that previously a univariate function f(u) would suffice, since I have code that is set up like that.

I suggest that the constructor could have some method that when provided with a univariate f(u) will construct the corresponding f(u,p) by creating some lambda (u,p) -> f(u). This looks a bit hacky, but would ensure backwards compatibility and be minimally invasive.

The most basic statement for a minimization problem is argmin_u( f(u) ) so it's unintuitive for a package that focuses on every type of optimization to not allow this.

Correct me if my assumptions are wrong, they're based on the discussion here:
https://github.com/SciML/Optimization.jl/issues/440

**Comment by tom-plaa** [comment]
I just rechecked, and my old code does already do this hack of passing the dummy variable. My point still stands as a nice to have, I guess...

**Comment by Vaibhavdixit02** [comment]
Answered in https://github.com/SciML/Optimization.jl/issues/440
