### ISSUE TITLE
isinplace check for DDEFunction

### ISSUE THREAD

**Issue by ErikQQY** [SciML/SciMLBase.jl#372]
I noticed some ```isinplace``` checks for ```DDEFunction``` are missing and the test coverage is low, do we need to set the inplace checks like what we did in ```ODEFunction```?

**Comment by ChrisRackauckas** [comment]
What kinds of checks?

**Comment by ErikQQY** [comment]
Sorry, that maybe not specific. I mean when I am defining my ```DDEFunction```, I think it would be great to throw error when I pass the wrong jacobian like what ```ODEFunction``` does:

![jac](https://user-images.githubusercontent.com/52615090/213839569-13938352-dd94-4268-a15a-49db182b498d.png)

**Comment by ChrisRackauckas** [comment]
oh yes that would be good to add
