### ISSUE TITLE
Scatterplot and lineplot use colour inconsistently

### ISSUE THREAD

**Issue by gustavdelius** [SciML/SciMLBase.jl#438]
When plotting a solution to a 2-dim problem, then blue is used for the first variable in a line plot but for the second variable in a scatter plot. For example
```
using OrdinaryDiffEq, Plots
function func!(du,u,p,t)
  du[1] = 1
  du[2] = 2
end
odeprob  = ODEProblem(func!,[1.0;1.0],(0.0,4.0))
odesol   = solve(odeprob, Tsit5(), saveat = 1)
plot(odesol)
scatter!(odesol)
```
![plot_8](https://user-images.githubusercontent.com/1340713/235377403-81281bc4-7fe3-4434-93f4-0476b25b5991.svg)

**Comment by ChrisRackauckas** [comment]
All of those colors are unique. Those are colors 1,2,3,4 in Plots.jl

**Comment by gustavdelius** [comment]
Ooops, sorry. With my strange colour vision I really should not comment on colours in plots. By the way: I am really impressed how quickly you respond to issue reports! Many thanks!

**Comment by ChrisRackauckas** [comment]
No worries 😅.  Take care. Note that Plots.jl has the ability to pick different color schemes, some of which are easier on some people's eyes. See https://docs.juliaplots.org/latest/generated/colorschemes/
