### ISSUE TITLE
PythonCall extension hangs precompilation

### ISSUE THREAD

**Issue by bgroenks96** [SciML/SciMLBase.jl#528]
The `PythonCall` extension for this package seems to hang the precompilation process indefinitely (or at least for a very long time).

Could precompilation be temporarily disabled until this issue resolved?

```
(test) pkg> st PythonCall
Status ...
  [6099a3de] PythonCall v0.9.14

(test) pkg> st SciMLBase
Status ...
  [0bca4576] SciMLBase v2.4.3
```

```
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 96 × Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, cascadelake)
  Threads: 96 on 96 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_IMAGE_THREADS = 1
```

**Comment by ChrisRackauckas** [comment]
Is this a standard Julia installation? I cannot seem to recreate this on any standard OS.

**Comment by bgroenks96** [comment]
Yes, it's a standard julia installation, but when I created an isolated environment with just `SciMLBase` and `PythonCall` it didn't happen anymore. So maybe it's an interaction with another package or with the `CondaPkg.toml` environment?

**Comment by bgroenks96** [comment]
Ok, the issue is resolved after purging `.CondaPkg`. My guess is maybe the issue was a lingering `lock` file or something. The SciMLBase extension was probably just coincidentally the first code to invoke `pyimport`. Since this is more of a general issue with precompilation and `CondaPkg`, I will close this for now.
