### ISSUE TITLE
Removal of parameter indexing of problems

### ISSUE THREAD

**Issue by isaacsas** [SciML/SciMLBase.jl#577]
If I understand:

https://github.com/SciML/SciMLBase.jl/blob/5340bea250016bf517cf25507548ecdf455ca053/src/problems/problem_interface.jl#L47

indexing a problem with a parameter is no longer consider valid. Shouldn't this still be a deprecation warning though and not an error until a breaking release is made? This is a user-facing change in the problem interface.

For example, this no longer works due to this message:
```julia
using ModelingToolkit
@variables t V(t)
@parameters k
D = Differential(t)
eq = [D(V) ~ -k*V]
@named osys = ODESystem(eq, t)
oprob = ODEProblem(osys, [V => 1.0], (0.0, 10.0), [k => 1.0])
oprob[k]
```

**Comment by ChrisRackauckas** [comment]
We had a breaking release on SymbolicIndexingInterface.jl. SciMLBase also just had one around the same time IIRC

**Comment by isaacsas** [comment]
The last SciMLBase breaking release was 2.0 in September right? Didn't that predate all the SII work? A deprecation warning was only added there like 3 weeks ago if I am reading the history right, and was then removed a few days ago. That really isn't enough time for people to become aware of the change without signifying a breaking release by going to V3.0.

It isn't a big deal, but I think this has likely broke some of Torkel's examples in the Catalyst docs since he was using this indexing feature in places.

**Comment by ChrisRackauckas** [comment]
The roll out of SII had started already at that time, it just took awhile to complete.

**Comment by isaacsas** [comment]
Got it. I'll close this then.
