### ISSUE TITLE
add remake option for `g` in `SDEProblem`

### ISSUE THREAD

**Issue by oameye** [SciML/SciMLBase.jl#735]
I would be nice to have a `remake` option for `g` in `SDEProblem`. I wanted to at the `g` kwarg in https://github.com/SciML/SciMLBase.jl/blob/8b207583c130fb897c344d2ac3742353ac2c596c/src/remake.jl#L234-L283

However, it seems a bit more involved as one can make a `SDEProblem` with `f::SDEFunction`. I think the best approach would be to add a `remake(::SDEFunction; kwargs)` method and add the following lines to the `remake(::SDEProblem; kwargs...)`:
```julia
if g !== missing
	if f isa SDEFunction
		f = remake(f; g=g)
	else
		f = SDEFuction(f, g)
	end
end
```
Do you agree? Is there some subtlety I am missing?

**Comment by ChrisRackauckas** [comment]
That looks like a reasonable way to do it.
