### ISSUE TITLE
potential logic error in solution interface

### ISSUE THREAD

**Issue by lamorton** [SciML/SciMLBase.jl#83]
It looks to me like [this](https://github.com/SciML/SciMLBase.jl/blob/9ac2da300e34bb84b4167aa3250d5aa6fe55876b/src/solutions/solution_interface.jl#L52-L53) is a mistake:
```julia
  if i == nothing
      if issymbollike(i) && Symbol(i) == getindepsym(A)
```

If `i` is `nothing` then it makes no sense to test whether it is symbol-like or is equal to the independent variable -- I think it's probably meant to be `sym` here instead of `i`.

**Comment by ChrisRackauckas** [comment]
@sharanry

**Comment by sharanry** [comment]
This might be a wider issue with RecursiveArrayTools too. https://github.com/SciML/RecursiveArrayTools.jl/blob/58d89af893261490dde31d1faf042b89b2270289/src/vector_of_array.jl#L75

Will look into it.

**Comment by sharanry** [comment]
I think we can close this? @ChrisRackauckas
