### ISSUE TITLE
Make remake error or at least warn when it can not correctly update a problem

### ISSUE THREAD

**Issue by isaacsas** [SciML/SciMLBase.jl#841]
Based on the recent discussion we've had, it seems there are a number of cases where remake can not update parameters / initial conditions as a user might desire. Given that remake is prevalent throughout SciML docs, this seems likely to cause silent bugs for many users. This is a problem for both ODE/DAE models, where users now need to know to communicate extra information, such as giving guesses, to guarantee that initialization will work correctly, but even more an issue for all other problem types (where there is no initialization that can be relied on to handle the updating remake can't do).

It would be helpful if remake itself could give errors or warnings when it encounters a case it can not handle correctly (at least as much as possible), so users are not surprised by its current behavior (which has also changed as of the last few SciMLBase releases, and so might also cause existing users problems in this new behavior).

edit: Perhaps there can be a kwarg, so users who understand the limitations and remake behavior can opt-out of checks for inputs it can't handle fully.

**Comment by ChrisRackauckas** [comment]
I think we just need a `lazy=false` keyword argument for this behavior. Though in general it's not possible to always to do this. So we should have `lazy=false` enable cycle detection, error if cycle, otherwise fixedpoint_sub.

**Comment by AayushSabharwal** [comment]
Cycle detection in SciMLBase will be limited to letting `fixpoint_sub` hit maxiters and erroring if the expression is still symbolic, since it doesn't have symbolic introspection capabilities available to it like MTK does.

**Comment by ChrisRackauckas** [comment]
Can't there be a detect_cycles function that is overloaded downstream?

**Comment by AayushSabharwal** [comment]
Yeah I guess that works
