### ISSUE TITLE
Stackoverflow with unexpected argument type to solution indexing

### ISSUE THREAD

**Issue by lamorton** [SciML/SciMLBase.jl#86]
When I accidentally tried to index an ODESolution using a character instead of a symbol, I got a stackoverflow.
```julia
using ModelingToolkit, OrdinaryDiffEq
@parameters α β δ γ
@variables t x(t) y(t) dx(t)
D = Differential(t)
eqs = [
  dx ~ α*x - β*x*y, 
  D(x) ~ dx,
  D(y) ~ -δ*y + γ*x*y
]
@named lv = ODESystem(eqs)
syss = structural_simplify(lv) 
parms = [α => 1.5, β => 1.0, δ => 3.0, γ => 1.0]
x0 = [x => 1.0, y => 1.0]
tsteps = 0.0:0.1:10.0
prob = ODEProblem(syss, x0, extrema(tsteps), parms, jac = true)
soltrue = solve(prob,  Tsit5(), saveat = tsteps);
soltrue['a'] #Stackoverflow
```

The culprit is [solution_interface.jl#60](https://github.com/SciML/SciMLBase.jl/blob/a3a1ac6d446f8fbcea7d0d32b7bfd527602763c2/src/solutions/solution_interface.jl#L60), which causes infinite recursion if you hit it with something that is neither an integer nor a symbol.

**Comment by ChrisRackauckas** [comment]
It would be good to throw a better error there, thanks. @sharanry ?
